########
# more settings

# markdown: kramdown

# pygments: true
highlighter: rouge

sass:
  sass_dir: css
  style:    expanded

# enable emojis
gems:
  - jemoji



exclude:
- README.md


safe: true
lsi: false

kramdown:
  input:	GFM
  hard_wrap:	TRUE